// Copyright 2024 Light Transport Entertainment Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Tiny OBJ parser/writer. Handles `v x y z`, `v x y z r g b` (vertex-colour
// extension), and `f a b c`, `f a/t a/t a/t`, `f a/t/n a/t/n a/t/n`,
// `f a//n a//n a//n`. Drops normals and uvs (they aren't round-tripped by
// the pamo pipeline).

export function parse(text) {
    const verts = [];
    const colors = [];
    const faces = [];
    let hasColor = false;

    for (const rawLine of text.split('\n')) {
        const line = rawLine.trim();
        if (line.length === 0 || line[0] === '#') continue;

        if (line[0] === 'v' && line[1] === ' ') {
            const t = line.slice(2).trim().split(/\s+/);
            if (t.length < 3) continue;
            verts.push(+t[0], +t[1], +t[2]);
            if (t.length >= 6) {
                hasColor = true;
                colors.push(+t[3], +t[4], +t[5]);
            } else {
                colors.push(0, 0, 0);
            }
        } else if (line[0] === 'f' && line[1] === ' ') {
            const tokens = line.slice(2).trim().split(/\s+/);
            if (tokens.length < 3) continue;
            const idx = tokens.map(t => parseInt(t.split('/')[0], 10) - 1);
            // Triangulate fan if quads/n-gons appear.
            for (let i = 1; i + 1 < idx.length; i++) {
                faces.push(idx[0], idx[i], idx[i + 1]);
            }
        }
    }

    return {
        verts: new Float32Array(verts),
        faces: new Int32Array(faces),
        colors: hasColor ? new Float32Array(colors) : null,
    };
}

export function serialise({ verts, faces, colors = null }) {
    const lines = ['# generated by pamo_c/web'];
    const nv = verts.length / 3;
    const nf = faces.length / 3;
    if (colors && colors.length === verts.length) {
        for (let i = 0; i < nv; i++) {
            lines.push(`v ${verts[i*3]} ${verts[i*3+1]} ${verts[i*3+2]} `
                       + `${colors[i*3]} ${colors[i*3+1]} ${colors[i*3+2]}`);
        }
    } else {
        for (let i = 0; i < nv; i++) {
            lines.push(`v ${verts[i*3]} ${verts[i*3+1]} ${verts[i*3+2]}`);
        }
    }
    for (let i = 0; i < nf; i++) {
        lines.push(`f ${faces[i*3] + 1} ${faces[i*3+1] + 1} ${faces[i*3+2] + 1}`);
    }
    lines.push('');
    return lines.join('\n');
}

// Compute axis-aligned bounding box and diameter of a Float32Array of
// xyz triplets. Useful for normalising the colour scale across meshes.
export function bounds(verts) {
    if (verts.length === 0) {
        return { min: [0, 0, 0], max: [0, 0, 0], diameter: 0 };
    }
    let minX = Infinity, minY = Infinity, minZ = Infinity;
    let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
    const n = verts.length / 3;
    for (let i = 0; i < n; i++) {
        const x = verts[i*3], y = verts[i*3+1], z = verts[i*3+2];
        if (x < minX) minX = x; if (x > maxX) maxX = x;
        if (y < minY) minY = y; if (y > maxY) maxY = y;
        if (z < minZ) minZ = z; if (z > maxZ) maxZ = z;
    }
    const dx = maxX - minX, dy = maxY - minY, dz = maxZ - minZ;
    return {
        min: [minX, minY, minZ],
        max: [maxX, maxY, maxZ],
        diameter: Math.sqrt(dx*dx + dy*dy + dz*dz),
    };
}
