// Copyright 2024 Light Transport Entertainment Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Tiny OBJ parser/writer. Handles `v x y z`, `v x y z r g b` (vertex-colour
// extension), and `f a b c`, `f a/t a/t a/t`, `f a/t/n a/t/n a/t/n`,
// `f a//n a//n a//n`. Drops normals and uvs (they aren't round-tripped by
// the pamo pipeline).

export function parse(text) {
    const verts = [];
    const colors = [];
    const faces = [];
    let hasColor = false;

    for (const rawLine of text.split('\n')) {
        const line = rawLine.trim();
        if (line.length === 0 || line[0] === '#') continue;

        if (line[0] === 'v' && line[1] === ' ') {
            const t = line.slice(2).trim().split(/\s+/);
            if (t.length < 3) continue;
            verts.push(+t[0], +t[1], +t[2]);
            if (t.length >= 6) {
                hasColor = true;
                colors.push(+t[3], +t[4], +t[5]);
            } else {
                colors.push(0, 0, 0);
            }
        } else if (line[0] === 'f' && line[1] === ' ') {
            const tokens = line.slice(2).trim().split(/\s+/);
            if (tokens.length < 3) continue;
            const idx = tokens.map(t => parseInt(t.split('/')[0], 10) - 1);
            // Triangulate fan if quads/n-gons appear.
            for (let i = 1; i + 1 < idx.length; i++) {
                faces.push(idx[0], idx[i], idx[i + 1]);
            }
        }
    }

    return {
        verts: new Float32Array(verts),
        faces: new Int32Array(faces),
        colors: hasColor ? new Float32Array(colors) : null,
    };
}

export function serialise({ verts, faces, colors = null }) {
    const lines = ['# generated by pamo_c/web'];
    const nv = verts.length / 3;
    const nf = faces.length / 3;
    if (colors && colors.length === verts.length) {
        for (let i = 0; i < nv; i++) {
            lines.push(`v ${verts[i*3]} ${verts[i*3+1]} ${verts[i*3+2]} `
                       + `${colors[i*3]} ${colors[i*3+1]} ${colors[i*3+2]}`);
        }
    } else {
        for (let i = 0; i < nv; i++) {
            lines.push(`v ${verts[i*3]} ${verts[i*3+1]} ${verts[i*3+2]}`);
        }
    }
    for (let i = 0; i < nf; i++) {
        lines.push(`f ${faces[i*3] + 1} ${faces[i*3+1] + 1} ${faces[i*3+2] + 1}`);
    }
    lines.push('');
    return lines.join('\n');
}

// Weld co-located vertices. Many real-world OBJs (especially scans /
// modeller exports of multi-part assemblies) ship with duplicate
// vertices at identical positions but distinct indices, so adjacent
// faces share a position but not a vertex ID. Simplification then sees
// the gap between them as a real boundary edge and pulls it open into
// a visible crack on the output. Welding by quantised position
// remaps faces onto a single ID per position before downstream
// processing.
//
// `epsRel` is a fraction of the mesh diameter (default 1e-4, ≈ a
// modeller's typical snap tolerance — 0.01% of diameter, so ~34 µm
// on a 0.3-unit mesh). Positions hashed into the same bucket are
// merged. 1e-6 is too tight: it only catches float32-noise dupes,
// not the slightly-off near-duplicates real modelling tools leave
// behind, so cracks still appear at simplification time.
//
// Returns { verts, faces, merged }: a new vert/face pair with the
// duplicates removed, plus the count of merged vertices for logging.
export function weldVertices(verts, faces, epsRel = 1e-4) {
    const n = verts.length / 3;
    if (n === 0) return { verts, faces, merged: 0 };
    const { diameter } = bounds(verts);
    const quantum = Math.max(diameter * epsRel, 1e-12);
    const inv = 1 / quantum;

    const map = new Map();          // "qx|qy|qz" → new vert idx
    const remap = new Int32Array(n);
    const newVerts = [];

    for (let i = 0; i < n; i++) {
        const x = verts[i*3], y = verts[i*3+1], z = verts[i*3+2];
        const qx = Math.round(x * inv);
        const qy = Math.round(y * inv);
        const qz = Math.round(z * inv);
        const key = `${qx}|${qy}|${qz}`;
        let nid = map.get(key);
        if (nid === undefined) {
            nid = newVerts.length / 3;
            newVerts.push(x, y, z);
            map.set(key, nid);
        }
        remap[i] = nid;
    }

    const newFaces = new Int32Array(faces.length);
    let nf = 0;
    for (let i = 0; i < faces.length; i += 3) {
        const a = remap[faces[i]];
        const b = remap[faces[i+1]];
        const c = remap[faces[i+2]];
        if (a === b || b === c || c === a) continue;   // degenerate
        newFaces[nf++] = a;
        newFaces[nf++] = b;
        newFaces[nf++] = c;
    }

    return {
        verts: new Float32Array(newVerts),
        faces: newFaces.subarray(0, nf),
        merged: n - (newVerts.length / 3),
    };
}

// Compute axis-aligned bounding box and diameter of a Float32Array of
// xyz triplets. Useful for normalising the colour scale across meshes.
export function bounds(verts) {
    if (verts.length === 0) {
        return { min: [0, 0, 0], max: [0, 0, 0], diameter: 0 };
    }
    let minX = Infinity, minY = Infinity, minZ = Infinity;
    let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
    const n = verts.length / 3;
    for (let i = 0; i < n; i++) {
        const x = verts[i*3], y = verts[i*3+1], z = verts[i*3+2];
        if (x < minX) minX = x; if (x > maxX) maxX = x;
        if (y < minY) minY = y; if (y > maxY) maxY = y;
        if (z < minZ) minZ = z; if (z > maxZ) maxZ = z;
    }
    const dx = maxX - minX, dy = maxY - minY, dz = maxZ - minZ;
    return {
        min: [minX, minY, minZ],
        max: [maxX, maxY, maxZ],
        diameter: Math.sqrt(dx*dx + dy*dy + dz*dz),
    };
}
